spring:
  application:
    name: eureka-customer             # others Eureka Client通过name调用所提供的服务

server:
  port: 8081

eureka:
  instance:
    hostname: localhost280608
  client:
    serviceUrl:                                  # 向Eureka Server进行服务注册(可声明多个)
      defaultZone: http://localhost:9090/eureka/ #,http://localhost:8762/eureka/
    enabled: true

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false